using System;

namespace test-dotnet-project-220026
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World from test-dotnet-project-220026!");
            Console.WriteLine("Generated by Scaffold Forge");
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }
    }
}